### ISSUE TITLE
GqlVars isn't filled in NewRelic

### ISSUE THREAD

**Issue by benoitemile** [localshred/apollo-newrelic-extension#2]
Following New Relic docs, addCustomAttribute method is expecting a string or a serializable type.

For now, variables is being passed as is, but if variables is an object, Gqlvars can't be filled and seen in newrelic errors because not correctly handled by node-newrelic.
ie : 
```js
{
  "foo": "bar"
}
```

I did a real quick pull request to fix that : 
https://github.com/localshred/apollo-newrelic-extension/pull/1

**Comment by tmullin-toast** [comment]
Corresponding message in `newrelic_agent.log`:
```
{"v":0,"level":40,"name":"newrelic","hostname":"redacted.local","pid":20597,"time":"2019-02-19T22:04:56.475Z","msg":"Not adding attribute gqlVars with object value type","component":"attributes"}
```

**Comment by vladanpaunovic** [comment]
@benoitemile, could you please solve this issue as it is resolved by #1 ?
Thank you for resolving this!

**Comment by benoitemile** [comment]
thank you

**Comment by benoitemile** [comment]
Could you please release a new version ?
