### ISSUE TITLE
apollo-newrelic-extension not working

### ISSUE THREAD

**Issue by madrahul1992** [localshred/apollo-newrelic-extension#3]
I am using it in Express server, it is not reporting to newrelic.
My implementation is as below:
const ApolloNewrelicExtension = require('apollo-newrelic-extension');

      extensions: () => {
        try {
          console.log('Yahan aar ahaan');
          new ApolloNewrelicExtension();
        } catch (error) {
          console.log("Error:: ", error); 
        }
      },

**Comment by solocommand** [comment]
@madrahul1992 I believe `extensions` needs to be an array. Try
```js
  extensions: [() => new ApolloNewrelicExtension()],
```

**Comment by localshred** [comment]
@solocommand is correct, wrap your extension in an array and it should work as expected.
