### ISSUE TITLE
Newrelic Credentials

### ISSUE THREAD

**Issue by anibaldeboni** [localshred/apollo-newrelic-extension#5]
Hi,

It didn't get it, how do I set my Newrelic creditials, like api-key or something? Thanks in advance.

**Comment by mlb6** [comment]
You can set that with the environment variables : 
https://docs.newrelic.com/docs/agents/nodejs-agent/installation-configuration/install-nodejs-agent#installing

**Comment by anibaldeboni** [comment]
figured it out latter bur forgot to close the issue. Thanks @mlb6
